# fly.toml app configuration file generated for hs-prescreen on 2023-05-23T13:54:38-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hs-prescreen"
primary_region = "sea"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
